[package]
name = "example"
version = "0.1.0"
authors = ["jmlb23 <jlb@ad.local>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
